name = "learnwithali"
compatibility_date = "2025-07-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "learnwithali-db"
database_id = "1af646d1-fffd-4ba6-834b-dd1da1806b9f"
